// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIioWveaZs__Qmbj7rI2rp1zyigBPO-HA',
    appId: '1:789737876581:web:5c53ce4f7f49d739a06a8c',
    messagingSenderId: '789737876581',
    projectId: 'expense-249aa',
    authDomain: 'expense-249aa.firebaseapp.com',
    storageBucket: 'expense-249aa.appspot.com',
    measurementId: 'G-K0HK3E1W3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7rytACeyqrYySbZBHz8tVY9hXQzQObhA',
    appId: '1:789737876581:android:b2017b686bc16d18a06a8c',
    messagingSenderId: '789737876581',
    projectId: 'expense-249aa',
    storageBucket: 'expense-249aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeJo3WV8J0VmEa9I8xO44tXFtgFOncPQ',
    appId: '1:789737876581:ios:af990d09ee5c49c6a06a8c',
    messagingSenderId: '789737876581',
    projectId: 'expense-249aa',
    storageBucket: 'expense-249aa.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeJo3WV8J0VmEa9I8xO44tXFtgFOncPQ',
    appId: '1:789737876581:ios:af990d09ee5c49c6a06a8c',
    messagingSenderId: '789737876581',
    projectId: 'expense-249aa',
    storageBucket: 'expense-249aa.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIioWveaZs__Qmbj7rI2rp1zyigBPO-HA',
    appId: '1:789737876581:web:b3aafedbc4af4e0aa06a8c',
    messagingSenderId: '789737876581',
    projectId: 'expense-249aa',
    authDomain: 'expense-249aa.firebaseapp.com',
    storageBucket: 'expense-249aa.appspot.com',
    measurementId: 'G-3JF7ZGHDHH',
  );
}
